baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '⋆ jpop'
theme = 'hugo-bearneo'

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

    [[menu.main]]
    identifier = "setupanduses"
    name = "Setup & uses"
    url = "/setupanduses/"
    weight = 2
